### ISSUE TITLE
import { bindTracked } from 'svelte3-redux' fails

### ISSUE THREAD

**Issue by drsounds** [dai-shi/svelte3-redux#1]
When doing
````js
import { bindTracked } from 'svelte3-redux'
````
it gives the error
Error: 'bindTracked' is not exported by node_modules/svelte3-redux/dist/index.umd.js

**Comment by dai-shi** [comment]
Hi!
Instead of dist/index.umd.js, you want to use dist/index.esm.js or dist/index.js for es modules or cjs.
I presume your bundler config prioritizes `"browser"` more than `"module"` or `"main"` in package.json.
I'm not very familiar with the svelte build system, but is this something like a normal environment?
Can I easily reproduce the error on my end?

**Comment by drsounds** [comment]
I resolved it by migrating the whole project to typescript.

**Comment by dai-shi** [comment]
Cool. Can you close the issue then?
